

export const GET_USERS = 'GET_USERS'
export const ADD_USER = 'ADD_USER'
export const CLEAR_USER = 'CLEAR_USER'
export const LOG_USER_OUT = 'LOG_USER_OUT'
export const LOGIN_USER = 'LOGIN_USER'
export const CREATE_USER = 'CREATE_USER'

export const GET_CONSTITUENCIES = 'GET_CONSTITUENCIES'

export const GET_ELECTION_DETAILS = 'GET_ELECTION_DETAILS'
export const GET_ELECTION_RESULT_DETAILS = 'GET_ELECTION_RESULT_DETAILS'

export const GET_CONSTITUENCY_CANDIDATES = 'GET_CONSTITUENCY_CANDIDATES'



export const SET_LOADING = 'SET_LOADING'